### ISSUE TITLE
Coach bags description

### ISSUE THREAD

**Issue by melanie-sun** [iris-shanghai/VR-CNY#10]
Hi Mike,

Could you please upload the description of Coach bags to the game? Attached is the copy.

[Copy of Coach bag selected.xlsx](https://github.com/iris-shanghai/VR-CNY/files/130435/Copy.of.Coach.bag.selected.xlsx)

Thanks,
Mel

**Comment by iamike** [comment]
Hi Melanie,
I have already deployed on staging site for you preview, and I have already send update to Olex.
http://cny-game.staging.iris-worldwide.cn/
pls review, thanks

Mike
