### ISSUE TITLE
Jan 25 bug lists 

### ISSUE THREAD

**Issue by iamike** [iris-shanghai/VR-CNY#7]
Hi Mike,

CNY几个修改点：
1. 活动说明的文字请替换成正确的
   fixed
2. 从选性别到选脸型的页面，刚进入的时候脸型选择已经在上面了，但是下面相关的icon外面没有黄色圈圈，请优化（图1）
   ![1](https://cloud.githubusercontent.com/assets/526854/12571852/4ffd25c6-c420-11e5-9c2e-37864c9e6aa1.PNG)
   fixed
3. 从脸型页（图1）到身体页（图2）脸的比例被压缩了（请两张图放在一起对比）
   ![2](https://cloud.githubusercontent.com/assets/526854/12571855/5802da9a-c420-11e5-98e9-3bc1007420b0.PNG)
   fixed
4. 图3头部出现错位，请检查下所有配对情况
   it shall be fixed, please give me some android phone for test
   ![3](https://cloud.githubusercontent.com/assets/526854/12571861/6c6d20b2-c420-11e5-84dd-cebd81d7e540.JPG)
5. 男士包包（图4中）第一个包包和第三个包包的信息弄反了，换一下

![4](https://cloud.githubusercontent.com/assets/526854/12571866/750c57c4-c420-11e5-90f5-20e3c8b5d0d3.PNG)
it shall be cache, please review
1. 从图4到图5，整个人物明显又被压缩了（请两张图放在一起对比）

![5](https://cloud.githubusercontent.com/assets/526854/12571872/8097dcee-c420-11e5-9430-4f85daa1bb5e.PNG)

it shall be fixed.
1. 客户反应整体精度看起来很低，请nango协助商量下解决方案
   I have scale down a little, so make resolution more higher.
2. 新年愿望，客户问我们能不能用比较有特色的手写体，请告知技术上是否可行
   it's very hard to make it consistance.
   but we can make text out of image. and set different font-family according to the reqirement. but font-family will be restricted to system of the smartphone.

**Comment by iamike** [comment]
Hi monica,
please review my comment below.
these changes will be affect on staging site after 5:30.

**Comment by MonicaLLLMMM** [comment]
sure thanks mike. Please give us a note after it's completed from both your side and olex's side.

**Comment by MonicaLLLMMM** [comment]
hi Mike,

上面第五个问题，1和3包包的信息（名字和货号），请重新对照excel表格看一下更新下。谢谢。

monica

**Comment by MonicaLLLMMM** [comment]
hi Mike

修改点如下：
1. 活动说明里面有两个日期改下：
   ![img_2154](https://cloud.githubusercontent.com/assets/16282946/12666656/cc4cb150-c67d-11e5-9248-a7af9fa794c9.PNG)
   fixed
   里面2016年1月26日至2月25日  改成  2016年1月29日至2月28日
   ![img_2155](https://cloud.githubusercontent.com/assets/16282946/12666673/facf5564-c67d-11e5-8ebc-371c2ce1a76f.PNG)
   里面2016年1月26日 改成1月29日
   2月25日 改成2月28日
2. 用户填写新年愿望
   ![img_2156](https://cloud.githubusercontent.com/assets/16282946/12666710/3bfd7cfa-c67e-11e5-9dc8-cda03f28618c.PNG)
   然后生成新年愿望，在生成的页面上（原本的图如下图）
   ![img_2157](https://cloud.githubusercontent.com/assets/16282946/12666728/53138ec0-c67e-11e5-91d2-6d0f072401fb.PNG)
   加一个奕欧来的签名 图片参考给你的psd
3. 分享以后好友点开链接后看到的第一个页面，原本的页面如下图
   ![img_2158](https://cloud.githubusercontent.com/assets/16282946/12666765/90955f80-c67e-11e5-9fab-d0d667947e4c.PNG)
   现在改成新的psd里面的文字和格式

今天我们尽快做好就上线，谢谢。

monica
